-- ============================================================
-- Sman Analysis Schema
-- 项目分析系统的 H2 数据库表结构
-- ============================================================

-- ============================================================
-- 分析循环状态表
-- 存储项目分析主循环的运行状态，用于断点续传
-- ============================================================
CREATE TABLE IF NOT EXISTS analysis_loop_state (
    project_key VARCHAR(255) PRIMARY KEY,
    enabled BOOLEAN DEFAULT TRUE,
    current_phase VARCHAR(50) DEFAULT 'IDLE',

    -- 当前分析任务（ING 状态）
    current_analysis_type VARCHAR(50),
    current_step INT DEFAULT 0,
    analysis_todos TEXT,  -- 待完成的分析任务列表（JSON 格式）

    -- 统计信息
    total_analyses INT DEFAULT 0,
    successful_analyses INT DEFAULT 0,

    -- 时间戳
    last_analysis_time BIGINT,
    last_analysis_time_readable VARCHAR(50),
    last_error TEXT,
    last_updated_at BIGINT NOT NULL
);

-- ============================================================
-- 分析结果表
-- 存储每种分析类型的执行结果和状态
-- ============================================================
CREATE TABLE IF NOT EXISTS analysis_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key VARCHAR(255) NOT NULL,
    analysis_type VARCHAR(50) NOT NULL,
    md_file_path VARCHAR(255),
    completeness DOUBLE DEFAULT 0.0,
    missing_sections TEXT,  -- 缺失的章节列表（JSON 格式）
    analysis_todos TEXT,    -- 该分析的待办事项（JSON 格式）
    task_status VARCHAR(20) DEFAULT 'PENDING',
    current_step INT DEFAULT 0,
    tool_call_history TEXT,  -- 工具调用历史（JSON 格式）
    created_at BIGINT NOT NULL,
    created_at_readable VARCHAR(50),
    updated_at BIGINT NOT NULL,
    updated_at_readable VARCHAR(50),

    -- 唯一约束：每个项目的每种分析类型只有一条记录
    CONSTRAINT uk_project_analysis UNIQUE (project_key, analysis_type)
);

-- 分析结果索引
CREATE INDEX IF NOT EXISTS idx_ar_project_key ON analysis_result(project_key);
CREATE INDEX IF NOT EXISTS idx_ar_status ON analysis_result(task_status);
CREATE INDEX IF NOT EXISTS idx_ar_type ON analysis_result(analysis_type);
